##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Thu Apr 06 18:29:51 CEST 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Nx_MQTT_Client


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/app_threadx.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
AZURE_RTOS/App/app_azure_rtos.c \
NetXDuo/App/app_netxduo.c \
../Drivers/BSP/STM32F4xx_Nucleo_144/stm32f4xx_nucleo_144.c \
Drivers/BSP/Components/lan8742/lan8742.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Core/Src/system_stm32f4xx.c \
Middlewares/ST/netxduo/common/drivers/ethernet/nx_stm32_eth_driver.c \
Middlewares/ST/netxduo/common/drivers/ethernet/lan8742/nx_stm32_phy_driver.c \
Middlewares/ST/netxduo/addons/mqtt/nxd_mqtt_client.c \
Middlewares/ST/netxduo/addons/dns/nxd_dns.c \
Middlewares/ST/netxduo/addons/dhcp/nxd_dhcp_client.c \
Middlewares/ST/netxduo/addons/dhcp/nxd_dhcpv6_client.c \
Middlewares/ST/netxduo/common/src/nx_arp_announce_send.c \
Middlewares/ST/netxduo/common/src/nx_arp_dynamic_entries_invalidate.c \
Middlewares/ST/netxduo/common/src/nx_arp_dynamic_entry_delete.c \
Middlewares/ST/netxduo/common/src/nx_arp_dynamic_entry_set.c \
Middlewares/ST/netxduo/common/src/nx_arp_enable.c \
Middlewares/ST/netxduo/common/src/nx_arp_entry_allocate.c \
Middlewares/ST/netxduo/common/src/nx_arp_entry_delete.c \
Middlewares/ST/netxduo/common/src/nx_arp_gratuitous_send.c \
Middlewares/ST/netxduo/common/src/nx_arp_hardware_address_find.c \
Middlewares/ST/netxduo/common/src/nx_arp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_arp_initialize.c \
Middlewares/ST/netxduo/common/src/nx_arp_interface_entries_delete.c \
Middlewares/ST/netxduo/common/src/nx_arp_ip_address_find.c \
Middlewares/ST/netxduo/common/src/nx_arp_packet_deferred_receive.c \
Middlewares/ST/netxduo/common/src/nx_arp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_arp_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_arp_periodic_update.c \
Middlewares/ST/netxduo/common/src/nx_arp_probe_send.c \
Middlewares/ST/netxduo/common/src/nx_arp_queue_process.c \
Middlewares/ST/netxduo/common/src/nx_arp_queue_send.c \
Middlewares/ST/netxduo/common/src/nx_arp_static_entries_delete.c \
Middlewares/ST/netxduo/common/src/nx_arp_static_entry_create.c \
Middlewares/ST/netxduo/common/src/nx_arp_static_entry_delete.c \
Middlewares/ST/netxduo/common/src/nx_arp_static_entry_delete_internal.c \
Middlewares/ST/netxduo/common/src/nx_icmp_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_icmp_enable.c \
Middlewares/ST/netxduo/common/src/nx_icmp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_icmp_interface_ping.c \
Middlewares/ST/netxduo/common/src/nx_icmp_interface_ping6.c \
Middlewares/ST/netxduo/common/src/nx_icmp_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_icmp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_icmp_ping.c \
Middlewares/ST/netxduo/common/src/nx_icmp_queue_process.c \
Middlewares/ST/netxduo/common/src/nx_icmpv4_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_icmpv4_process_echo_reply.c \
Middlewares/ST/netxduo/common/src/nx_icmpv4_process_echo_request.c \
Middlewares/ST/netxduo/common/src/nx_icmpv4_send_error_message.c \
Middlewares/ST/netxduo/common/src/nx_igmp_enable.c \
Middlewares/ST/netxduo/common/src/nx_igmp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_igmp_interface_report_send.c \
Middlewares/ST/netxduo/common/src/nx_igmp_loopback_disable.c \
Middlewares/ST/netxduo/common/src/nx_igmp_loopback_enable.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_check.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_interface_join_internal.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_interface_leave_internal.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_join.c \
Middlewares/ST/netxduo/common/src/nx_igmp_multicast_leave.c \
Middlewares/ST/netxduo/common/src/nx_igmp_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_igmp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_igmp_periodic_processing.c \
Middlewares/ST/netxduo/common/src/nx_igmp_queue_process.c \
Middlewares/ST/netxduo/common/src/nx_invalidate_destination_entry.c \
Middlewares/ST/netxduo/common/src/nx_ip_address_change_notify.c \
Middlewares/ST/netxduo/common/src/nx_ip_address_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_address_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_auxiliary_packet_pool_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_checksum_compute.c \
Middlewares/ST/netxduo/common/src/nx_ip_create.c \
Middlewares/ST/netxduo/common/src/nx_ip_deferred_link_status_process.c \
Middlewares/ST/netxduo/common/src/nx_ip_delete.c \
Middlewares/ST/netxduo/common/src/nx_ip_delete_queue_clear.c \
Middlewares/ST/netxduo/common/src/nx_ip_dispatch_process.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_deferred_enable.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_deferred_processing.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_deferred_receive.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_direct_command.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_interface_direct_command.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_link_status_event.c \
Middlewares/ST/netxduo/common/src/nx_ip_driver_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_ip_fast_periodic_timer_entry.c \
Middlewares/ST/netxduo/common/src/nx_ip_forward_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_ip_forwarding_disable.c \
Middlewares/ST/netxduo/common/src/nx_ip_forwarding_enable.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_assembly.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_disable.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_enable.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_forward_packet.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_packet.c \
Middlewares/ST/netxduo/common/src/nx_ip_fragment_timeout_check.c \
Middlewares/ST/netxduo/common/src/nx_ip_gateway_address_clear.c \
Middlewares/ST/netxduo/common/src/nx_ip_gateway_address_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_gateway_address_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_header_add.c \
Middlewares/ST/netxduo/common/src/nx_ip_info_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_initialize.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_address_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_address_mapping_configure.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_address_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_attach.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_capability_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_capability_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_detach.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_info_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_mtu_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_physical_address_get.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_physical_address_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_interface_status_check.c \
Middlewares/ST/netxduo/common/src/nx_ip_link_status_change_notify_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_max_payload_size_find.c \
Middlewares/ST/netxduo/common/src/nx_ip_packet_checksum_compute.c \
Middlewares/ST/netxduo/common/src/nx_ip_packet_deferred_receive.c \
Middlewares/ST/netxduo/common/src/nx_ip_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_ip_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_ip_periodic_timer_entry.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_disable.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_enable.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_filter_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_processing.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_packet_source_send.c \
Middlewares/ST/netxduo/common/src/nx_ip_raw_receive_queue_max_set.c \
Middlewares/ST/netxduo/common/src/nx_ip_route_find.c \
Middlewares/ST/netxduo/common/src/nx_ip_static_route_add.c \
Middlewares/ST/netxduo/common/src/nx_ip_static_route_delete.c \
Middlewares/ST/netxduo/common/src/nx_ip_status_check.c \
Middlewares/ST/netxduo/common/src/nx_ip_thread_entry.c \
Middlewares/ST/netxduo/common/src/nx_ipv4_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nx_ipv4_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nx_ipv4_option_process.c \
Middlewares/ST/netxduo/common/src/nx_ipv4_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_md5.c \
Middlewares/ST/netxduo/common/src/nx_packet_allocate.c \
Middlewares/ST/netxduo/common/src/nx_packet_copy.c \
Middlewares/ST/netxduo/common/src/nx_packet_data_adjust.c \
Middlewares/ST/netxduo/common/src/nx_packet_data_append.c \
Middlewares/ST/netxduo/common/src/nx_packet_data_extract_offset.c \
Middlewares/ST/netxduo/common/src/nx_packet_data_retrieve.c \
Middlewares/ST/netxduo/common/src/nx_packet_debug_info_get.c \
Middlewares/ST/netxduo/common/src/nx_packet_length_get.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_create.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_delete.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_info_get.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_initialize.c \
Middlewares/ST/netxduo/common/src/nx_packet_pool_low_watermark_set.c \
Middlewares/ST/netxduo/common/src/nx_packet_release.c \
Middlewares/ST/netxduo/common/src/nx_packet_transmit_release.c \
Middlewares/ST/netxduo/common/src/nx_ram_network_driver.c \
Middlewares/ST/netxduo/common/src/nx_rarp_disable.c \
Middlewares/ST/netxduo/common/src/nx_rarp_enable.c \
Middlewares/ST/netxduo/common/src/nx_rarp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_rarp_packet_deferred_receive.c \
Middlewares/ST/netxduo/common/src/nx_rarp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_rarp_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_rarp_periodic_update.c \
Middlewares/ST/netxduo/common/src/nx_rarp_queue_process.c \
Middlewares/ST/netxduo/common/src/nx_system_initialize.c \
Middlewares/ST/netxduo/common/src/nx_tcp_cleanup_deferred.c \
Middlewares/ST/netxduo/common/src/nx_tcp_client_bind_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_client_socket_bind.c \
Middlewares/ST/netxduo/common/src/nx_tcp_client_socket_connect.c \
Middlewares/ST/netxduo/common/src/nx_tcp_client_socket_port_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_client_socket_unbind.c \
Middlewares/ST/netxduo/common/src/nx_tcp_connect_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_deferred_cleanup_check.c \
Middlewares/ST/netxduo/common/src/nx_tcp_disconnect_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_enable.c \
Middlewares/ST/netxduo/common/src/nx_tcp_fast_periodic_processing.c \
Middlewares/ST/netxduo/common/src/nx_tcp_free_port_find.c \
Middlewares/ST/netxduo/common/src/nx_tcp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_initialize.c \
Middlewares/ST/netxduo/common/src/nx_tcp_mss_option_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_no_connection_reset.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_ack.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_control.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_fin.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_probe.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_rst.c \
Middlewares/ST/netxduo/common/src/nx_tcp_packet_send_syn.c \
Middlewares/ST/netxduo/common/src/nx_tcp_periodic_processing.c \
Middlewares/ST/netxduo/common/src/nx_tcp_queue_process.c \
Middlewares/ST/netxduo/common/src/nx_tcp_receive_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_accept.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_listen.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_relisten.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_unaccept.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_unlisten.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_block_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_bytes_available.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_connection_reset.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_create.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_delete.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_disconnect.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_disconnect_complete_notify.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_establish_notify.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_info_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_mss_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_mss_peer_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_mss_set.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_peer_info_get.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_queue_depth_notify_set.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_receive.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_receive_notify.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_receive_queue_flush.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_receive_queue_max_set.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_retransmit.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_send.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_send_internal.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_ack_check.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_closing.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_data_check.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_established.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_fin_wait1.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_fin_wait2.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_last_ack.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_syn_received.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_syn_sent.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_transmit_check.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_state_wait.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_thread_resume.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_thread_suspend.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_timed_wait_callback.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_transmit_configure.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_transmit_queue_flush.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_window_update_notify_set.c \
Middlewares/ST/netxduo/common/src/nx_tcp_transmit_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_tcp_window_scaling_option_get.c \
Middlewares/ST/netxduo/common/src/nx_udp_bind_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_udp_enable.c \
Middlewares/ST/netxduo/common/src/nx_udp_free_port_find.c \
Middlewares/ST/netxduo/common/src/nx_udp_info_get.c \
Middlewares/ST/netxduo/common/src/nx_udp_packet_info_extract.c \
Middlewares/ST/netxduo/common/src/nx_udp_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_udp_receive_cleanup.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_bind.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_bytes_available.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_checksum_disable.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_checksum_enable.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_create.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_delete.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_info_get.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_port_get.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_receive.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_receive_notify.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_send.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_source_send.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_unbind.c \
Middlewares/ST/netxduo/common/src/nx_udp_source_extract.c \
Middlewares/ST/netxduo/common/src/nx_utility.c \
Middlewares/ST/netxduo/common/src/nxd_icmp_enable.c \
Middlewares/ST/netxduo/common/src/nxd_icmp_ping.c \
Middlewares/ST/netxduo/common/src/nxd_icmp_source_ping.c \
Middlewares/ST/netxduo/common/src/nxd_ip_raw_packet_send.c \
Middlewares/ST/netxduo/common/src/nxd_ip_raw_packet_source_send.c \
Middlewares/ST/netxduo/common/src/nxd_tcp_client_socket_connect.c \
Middlewares/ST/netxduo/common/src/nxd_tcp_socket_peer_info_get.c \
Middlewares/ST/netxduo/common/src/nxd_udp_packet_info_extract.c \
Middlewares/ST/netxduo/common/src/nxd_udp_socket_send.c \
Middlewares/ST/netxduo/common/src/nxd_udp_socket_source_send.c \
Middlewares/ST/netxduo/common/src/nxd_udp_source_extract.c \
Middlewares/ST/netxduo/common/src/nxde_icmp_enable.c \
Middlewares/ST/netxduo/common/src/nxde_icmp_ping.c \
Middlewares/ST/netxduo/common/src/nxde_icmp_source_ping.c \
Middlewares/ST/netxduo/common/src/nxde_ip_raw_packet_send.c \
Middlewares/ST/netxduo/common/src/nxde_ip_raw_packet_source_send.c \
Middlewares/ST/netxduo/common/src/nxde_tcp_client_socket_connect.c \
Middlewares/ST/netxduo/common/src/nxde_tcp_socket_peer_info_get.c \
Middlewares/ST/netxduo/common/src/nxde_udp_packet_info_extract.c \
Middlewares/ST/netxduo/common/src/nxde_udp_socket_send.c \
Middlewares/ST/netxduo/common/src/nxde_udp_socket_source_send.c \
Middlewares/ST/netxduo/common/src/nxde_udp_source_extract.c \
Middlewares/ST/netxduo/common/src/nxe_arp_dynamic_entries_invalidate.c \
Middlewares/ST/netxduo/common/src/nxe_arp_dynamic_entry_set.c \
Middlewares/ST/netxduo/common/src/nxe_arp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_arp_entry_delete.c \
Middlewares/ST/netxduo/common/src/nxe_arp_gratuitous_send.c \
Middlewares/ST/netxduo/common/src/nxe_arp_hardware_address_find.c \
Middlewares/ST/netxduo/common/src/nxe_arp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_arp_ip_address_find.c \
Middlewares/ST/netxduo/common/src/nxe_arp_static_entries_delete.c \
Middlewares/ST/netxduo/common/src/nxe_arp_static_entry_create.c \
Middlewares/ST/netxduo/common/src/nxe_arp_static_entry_delete.c \
Middlewares/ST/netxduo/common/src/nxe_icmp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_icmp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_icmp_ping.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_loopback_disable.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_loopback_enable.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_multicast_join.c \
Middlewares/ST/netxduo/common/src/nxe_igmp_multicast_leave.c \
Middlewares/ST/netxduo/common/src/nxe_ip_address_change_notify.c \
Middlewares/ST/netxduo/common/src/nxe_ip_address_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_address_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_auxiliary_packet_pool_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_create.c \
Middlewares/ST/netxduo/common/src/nxe_ip_delete.c \
Middlewares/ST/netxduo/common/src/nxe_ip_driver_direct_command.c \
Middlewares/ST/netxduo/common/src/nxe_ip_driver_interface_direct_command.c \
Middlewares/ST/netxduo/common/src/nxe_ip_forwarding_disable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_forwarding_enable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_fragment_disable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_fragment_enable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_gateway_address_clear.c \
Middlewares/ST/netxduo/common/src/nxe_ip_gateway_address_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_gateway_address_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_address_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_address_mapping_configure.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_address_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_attach.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_capability_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_capability_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_detach.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_mtu_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_physical_address_get.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_physical_address_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_interface_status_check.c \
Middlewares/ST/netxduo/common/src/nxe_ip_link_status_change_notify_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_max_payload_size_find.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_disable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_enable.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_filter_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_receive.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_send.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_packet_source_send.c \
Middlewares/ST/netxduo/common/src/nxe_ip_raw_receive_queue_max_set.c \
Middlewares/ST/netxduo/common/src/nxe_ip_static_route_add.c \
Middlewares/ST/netxduo/common/src/nxe_ip_static_route_delete.c \
Middlewares/ST/netxduo/common/src/nxe_ip_status_check.c \
Middlewares/ST/netxduo/common/src/nxe_ipv4_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nxe_ipv4_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nxe_packet_allocate.c \
Middlewares/ST/netxduo/common/src/nxe_packet_copy.c \
Middlewares/ST/netxduo/common/src/nxe_packet_data_append.c \
Middlewares/ST/netxduo/common/src/nxe_packet_data_extract_offset.c \
Middlewares/ST/netxduo/common/src/nxe_packet_data_retrieve.c \
Middlewares/ST/netxduo/common/src/nxe_packet_length_get.c \
Middlewares/ST/netxduo/common/src/nxe_packet_pool_create.c \
Middlewares/ST/netxduo/common/src/nxe_packet_pool_delete.c \
Middlewares/ST/netxduo/common/src/nxe_packet_pool_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_packet_pool_low_watermark_set.c \
Middlewares/ST/netxduo/common/src/nxe_packet_release.c \
Middlewares/ST/netxduo/common/src/nxe_packet_transmit_release.c \
Middlewares/ST/netxduo/common/src/nxe_rarp_disable.c \
Middlewares/ST/netxduo/common/src/nxe_rarp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_rarp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_client_socket_bind.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_client_socket_connect.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_client_socket_port_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_client_socket_unbind.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_free_port_find.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_server_socket_accept.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_server_socket_listen.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_server_socket_relisten.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_server_socket_unaccept.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_server_socket_unlisten.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_bytes_available.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_create.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_delete.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_disconnect.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_disconnect_complete_notify.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_establish_notify.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_mss_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_mss_peer_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_mss_set.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_peer_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_queue_depth_notify_set.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_receive.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_receive_notify.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_receive_queue_max_set.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_send.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_state_wait.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_timed_wait_callback.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_transmit_configure.c \
Middlewares/ST/netxduo/common/src/nxe_tcp_socket_window_update_notify_set.c \
Middlewares/ST/netxduo/common/src/nxe_udp_enable.c \
Middlewares/ST/netxduo/common/src/nxe_udp_free_port_find.c \
Middlewares/ST/netxduo/common/src/nxe_udp_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_udp_packet_info_extract.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_bind.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_bytes_available.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_checksum_disable.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_checksum_enable.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_create.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_delete.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_info_get.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_port_get.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_receive.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_receive_notify.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_send.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_source_send.c \
Middlewares/ST/netxduo/common/src/nxe_udp_socket_unbind.c \
Middlewares/ST/netxduo/common/src/nxe_udp_source_extract.c \
Middlewares/ST/netxduo/common/src/nx_icmp_ping6.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_DAD_clear_NDCache_entry.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_DAD_failure.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_dest_table_add.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_dest_table_find.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_destination_table_periodic_update.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_packet_process.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_perform_DAD.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_echo_reply.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_echo_request.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_na.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_ns.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_packet_too_big.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_ra.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_process_redirect.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_send_error_message.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_send_ns.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_send_queued_packets.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_send_rs.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_validate_neighbor_message.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_validate_options.c \
Middlewares/ST/netxduo/common/src/nx_icmpv6_validate_ra.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_fragment_process.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_header_add.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_multicast_join.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_multicast_leave.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_option_error.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_packet_copy.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_packet_send.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_prefix_list_add_entry.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_prefix_list_delete.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_prefix_list_delete_entry.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_process_fragment_option.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_process_hop_by_hop_option.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_process_routing_option.c \
Middlewares/ST/netxduo/common/src/nx_ipv6_util.c \
Middlewares/ST/netxduo/common/src/nxd_icmpv6_ra_flag_callback_set.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_address_change_notify.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_address_delete.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_address_get.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_address_set.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_add.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_add_internal.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_delete.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_entry_get.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_get.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_number_of_entries_get.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_default_router_table_init.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_destination_table_find_next_hop.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_disable.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_enable.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_find_default_router_from_address.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_find_max_prefix_length.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_interface_find.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_prefix_router_timer_tick.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_raw_packet_send_internal.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_router_lookup.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_router_solicitation_check.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_search_onlink.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_stateless_address_autoconfig_disable.c \
Middlewares/ST/netxduo/common/src/nxd_ipv6_stateless_address_autoconfig_enable.c \
Middlewares/ST/netxduo/common/src/nxde_icmpv6_ra_flag_callback_set.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_address_change_notify.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_address_delete.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_address_get.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_address_set.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_default_router_add.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_default_router_delete.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_default_router_entry_get.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_default_router_get.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_default_router_number_of_entries_get.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_disable.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_enable.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_multicast_interface_join.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_multicast_interface_leave.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_stateless_address_autoconfig_disable.c \
Middlewares/ST/netxduo/common/src/nxde_ipv6_stateless_address_autoconfig_enable.c \
Middlewares/ST/netxduo/common/src/nxd_nd_cache_entry_delete.c \
Middlewares/ST/netxduo/common/src/nxd_nd_cache_entry_set.c \
Middlewares/ST/netxduo/common/src/nxd_nd_cache_hardware_address_find.c \
Middlewares/ST/netxduo/common/src/nxd_nd_cache_invalidate.c \
Middlewares/ST/netxduo/common/src/nxd_nd_cache_ip_address_find.c \
Middlewares/ST/netxduo/common/src/nx_tcp_server_socket_driver_listen.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_driver_establish.c \
Middlewares/ST/netxduo/common/src/nx_tcp_socket_driver_packet_receive.c \
Middlewares/ST/netxduo/common/src/nx_udp_socket_driver_packet_receive.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_allocate_handshake_packet.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_client_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_client_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_client_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_ecc_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_hash_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_packet_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_process_clienthello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_process_handshake_header.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_process_header.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_process_helloverifyrequest.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_process_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_receive_callback.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_retransmit.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_retransmit_queue_flush.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_send_clienthello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_send_handshake_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_send_helloverifyrequest.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_send_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_send_serverhello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_create.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_ecc_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_notify_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_start.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_stop.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_cache.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_client_info_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_create.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_end.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_receive.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_reset.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_check.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_sliding_window_update.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_dtls_verify_mac.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_module_hash_compute.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_client_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_crypto_init.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_generate_keys.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_server_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_session_keys_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_active_certificate_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_allocate_handshake_packet.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_check_protocol_version.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_ciphersuite_lookup.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_client_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_client_psk_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_ecc_generate_keys.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_ecc_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_find_curve_method.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_finished_hash_generate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_generate_keys.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_generate_premaster_secret.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_init.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_handshake_hash_update.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_handshake_process.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_hash_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_key_material_init.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_local_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_map_error_to_alert.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_metadata_size_calculate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_newest_supported_version.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_packet_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_packet_release.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_certificate_request.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_certificate_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_changecipherspec.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_client_key_exchange.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_clienthello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_clienthello_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_encrypted_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_finished.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_handshake_header.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_header.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_newsessionticket.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_remote_certificate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_server_key_exchange.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_serverhello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_process_serverhello_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_protocol_version_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_psk_binder_generate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_psk_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_psk_identity_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_record_hash_calculate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_record_hash_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_record_hash_update.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_record_payload_decrypt.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_record_payload_encrypt.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_free_all.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_remote_certificate_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_alert.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_certificate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_certificate_request.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_certificate_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_changecipherspec.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_client_key_exchange.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_clienthello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_clienthello_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_encrypted_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_finished.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_handshake_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_hellorequest.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_newsessionticket.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_record.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_server_key_exchange.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_serverhello.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_send_serverhello_extensions.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_server_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_server_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_server_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_server_handshake.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_alert_value_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_certificate_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_client_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_disable.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_client_verify_enable.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_create.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_create_ext.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_end.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_iv_size_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_keys_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_packet_buffer_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_receive.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_receive_records.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_reset.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_server_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_sni_extension_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_time_function_set.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_shutdown.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_tls_verify_mac.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_chain_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_list_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_list_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_list_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_certificate_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_common_name_dns_check.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_crl_revocation_check.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_crl_verify.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_compare.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_distinguished_name_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_dns_name_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_ec_private_key_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_expiration_check.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_extension_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_find_certificate_methods.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_find_curve_method.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_free_certificate_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_key_usage_extension_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_local_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_local_device_certificate_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_oid_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_pkcs7_decode.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_store_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_store_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_store_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_subject_alt_names_find.c \
Middlewares/ST/netxduo/nx_secure/src/nx_secure_x509_wildcard_compare.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_client_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_client_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_ecc_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_packet_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_create.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_ecc_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_notify_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_start.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_stop.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_client_info_get.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_create.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_end.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_receive.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_reset.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_active_certificate_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_client_psk_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_local_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_metadata_size_calculate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_packet_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_psk_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_remote_certificate_free_all.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_find.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_server_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_alert_value_get.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_certificate_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_client_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_disable.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_client_verify_enable.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_create.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_delete.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_end.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_packet_buffer_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_protocol_version_override.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_receive.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_reset.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_send.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_server_callback_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_sni_extension_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_start.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_time_function_set.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_add.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_tls_trusted_certificate_remove.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_certificate_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_common_name_dns_check.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_crl_revocation_check.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_dns_name_initialize.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_extension_find.c \
Middlewares/ST/netxduo/nx_secure/src/nxe_secure_x509_key_usage_extension_parse.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_3des.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_aes.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_cbc.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ccm.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ctr.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_des.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_dh.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_drbg.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec_secp192r1_fixed_points.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec_secp224r1_fixed_points.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec_secp256r1_fixed_points.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec_secp384r1_fixed_points.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ec_secp521r1_fixed_points.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ecdh.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ecdsa.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_ecjpake.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_gcm.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_generic_ciphersuites.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hkdf.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hmac.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hmac_md5.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hmac_sha1.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hmac_sha2.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_hmac_sha5.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_huge_number.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_huge_number_extended.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_initialize.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_md5.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_methods.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_module_start.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_null_cipher.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_phash.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_pkcs1_v1.5.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_rsa.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_sha1.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_sha2.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_sha5.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_tls_prf_1.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_tls_prf_sha256.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_tls_prf_sha384.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_tls_prf_sha512.c \
Middlewares/ST/netxduo/crypto_libraries/src/nx_crypto_xcbc_mac.c \
Middlewares/ST/threadx/common/src/tx_initialize_high_level.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.c \
Middlewares/ST/threadx/common/src/tx_block_allocate.c \
Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_block_pool_create.c \
Middlewares/ST/threadx/common/src/tx_block_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_block_release.c \
Middlewares/ST/threadx/common/src/tx_byte_allocate.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_create.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_search.c \
Middlewares/ST/threadx/common/src/tx_byte_release.c \
Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.c \
Middlewares/ST/threadx/common/src/tx_event_flags_create.c \
Middlewares/ST/threadx/common/src/tx_event_flags_delete.c \
Middlewares/ST/threadx/common/src/tx_event_flags_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_initialize.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/tx_mutex_cleanup.c \
Middlewares/ST/threadx/common/src/tx_mutex_create.c \
Middlewares/ST/threadx/common/src/tx_mutex_delete.c \
Middlewares/ST/threadx/common/src/tx_mutex_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_initialize.c \
Middlewares/ST/threadx/common/src/tx_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/tx_mutex_priority_change.c \
Middlewares/ST/threadx/common/src/tx_mutex_put.c \
Middlewares/ST/threadx/common/src/tx_queue_cleanup.c \
Middlewares/ST/threadx/common/src/tx_queue_create.c \
Middlewares/ST/threadx/common/src/tx_queue_delete.c \
Middlewares/ST/threadx/common/src/tx_queue_flush.c \
Middlewares/ST/threadx/common/src/tx_queue_front_send.c \
Middlewares/ST/threadx/common/src/tx_queue_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_initialize.c \
Middlewares/ST/threadx/common/src/tx_queue_prioritize.c \
Middlewares/ST/threadx/common/src/tx_queue_receive.c \
Middlewares/ST/threadx/common/src/tx_queue_send.c \
Middlewares/ST/threadx/common/src/tx_queue_send_notify.c \
Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.c \
Middlewares/ST/threadx/common/src/tx_semaphore_create.c \
Middlewares/ST/threadx/common/src/tx_semaphore_delete.c \
Middlewares/ST/threadx/common/src/tx_semaphore_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_initialize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_create.c \
Middlewares/ST/threadx/common/src/tx_thread_delete.c \
Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_identify.c \
Middlewares/ST/threadx/common/src/tx_thread_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_initialize.c \
Middlewares/ST/threadx/common/src/tx_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/tx_thread_priority_change.c \
Middlewares/ST/threadx/common/src/tx_thread_relinquish.c \
Middlewares/ST/threadx/common/src/tx_thread_reset.c \
Middlewares/ST/threadx/common/src/tx_thread_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_shell_entry.c \
Middlewares/ST/threadx/common/src/tx_thread_sleep.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.c \
Middlewares/ST/threadx/common/src/tx_thread_system_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_system_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_terminate.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/tx_thread_timeout.c \
Middlewares/ST/threadx/common/src/tx_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_time_get.c \
Middlewares/ST/threadx/common/src/tx_time_set.c \
Middlewares/ST/threadx/common/src/txe_block_allocate.c \
Middlewares/ST/threadx/common/src/txe_block_pool_create.c \
Middlewares/ST/threadx/common/src/txe_block_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_block_release.c \
Middlewares/ST/threadx/common/src/txe_byte_allocate.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_create.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_byte_release.c \
Middlewares/ST/threadx/common/src/txe_event_flags_create.c \
Middlewares/ST/threadx/common/src/txe_event_flags_delete.c \
Middlewares/ST/threadx/common/src/txe_event_flags_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/txe_mutex_create.c \
Middlewares/ST/threadx/common/src/txe_mutex_delete.c \
Middlewares/ST/threadx/common/src/txe_mutex_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_info_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/txe_mutex_put.c \
Middlewares/ST/threadx/common/src/txe_queue_create.c \
Middlewares/ST/threadx/common/src/txe_queue_delete.c \
Middlewares/ST/threadx/common/src/txe_queue_flush.c \
Middlewares/ST/threadx/common/src/txe_queue_front_send.c \
Middlewares/ST/threadx/common/src/txe_queue_info_get.c \
Middlewares/ST/threadx/common/src/txe_queue_prioritize.c \
Middlewares/ST/threadx/common/src/txe_queue_receive.c \
Middlewares/ST/threadx/common/src/txe_queue_send.c \
Middlewares/ST/threadx/common/src/txe_queue_send_notify.c \
Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_create.c \
Middlewares/ST/threadx/common/src/txe_semaphore_delete.c \
Middlewares/ST/threadx/common/src/txe_semaphore_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_create.c \
Middlewares/ST/threadx/common/src/txe_thread_delete.c \
Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_info_get.c \
Middlewares/ST/threadx/common/src/txe_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/txe_thread_priority_change.c \
Middlewares/ST/threadx/common/src/txe_thread_relinquish.c \
Middlewares/ST/threadx/common/src/txe_thread_reset.c \
Middlewares/ST/threadx/common/src/txe_thread_resume.c \
Middlewares/ST/threadx/common/src/txe_thread_suspend.c \
Middlewares/ST/threadx/common/src/txe_thread_terminate.c \
Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/txe_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_timer_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_change.c \
Middlewares/ST/threadx/common/src/tx_timer_create.c \
Middlewares/ST/threadx/common/src/tx_timer_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_delete.c \
Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c \
Middlewares/ST/threadx/common/src/tx_timer_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_initialize.c \
Middlewares/ST/threadx/common/src/tx_timer_system_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c \
Middlewares/ST/threadx/common/src/txe_timer_activate.c \
Middlewares/ST/threadx/common/src/txe_timer_change.c \
Middlewares/ST/threadx/common/src/txe_timer_create.c \
Middlewares/ST/threadx/common/src/txe_timer_deactivate.c \
Middlewares/ST/threadx/common/src/txe_timer_delete.c \
Middlewares/ST/threadx/common/src/txe_timer_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_performance_system_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_performance_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_performance_system_info_get.c  

# ASM sources
ASM_SOURCES =  \
startup_stm32f429xx.s \
Core/Src/tx_initialize_low_level.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DTX_INCLUDE_USER_DEFINE_FILE \
-DNX_INCLUDE_USER_DEFINE_FILE \
-DUSE_HAL_DRIVER \
-DSTM32F429xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IAZURE_RTOS/App \
-INetXDuo/App \
-INetXDuo/Target \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/BSP/Components/lan8742/ \
-IMiddlewares/ST/netxduo/common/drivers/ethernet/ \
-IMiddlewares/ST/netxduo/addons/mqtt/ \
-IMiddlewares/ST/netxduo/addons/dns/ \
-IMiddlewares/ST/netxduo/addons/dhcp/ \
-IMiddlewares/ST/netxduo/common/inc/ \
-IMiddlewares/ST/netxduo/ports/cortex_m4/gnu/inc/ \
-IMiddlewares/ST/netxduo/nx_secure/inc/ \
-IMiddlewares/ST/netxduo/nx_secure/ports/ \
-IMiddlewares/ST/netxduo/crypto_libraries/inc/ \
-IMiddlewares/ST/netxduo/crypto_libraries/ports/cortex_m4/gnu/inc/ \
-IMiddlewares/ST/netxduo/crypto_libraries/ports/cortex_m4/ac6/inc/ \
-IMiddlewares/ST/threadx/common/inc/ \
-IMiddlewares/ST/threadx/ports/cortex_m4/gnu/inc/ \
-I../Drivers/BSP/STM32F4xx_Nucleo_144


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F429ZITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***